piVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"vegastobackend"},"name":"vegasto-deployment","namespace":"student-t-stadler1"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"vegastobackend"}},"template":{"metadata":{"labels":{"app":"vegastobackend"}},"spec":{"containers":[{"image":"zauner/vegastrobackend:latest","imagePullPolicy":"Always","name":"vegastro-backend","ports":[{"containerPort":3000,"protocol":"TCP"}],"resources":{"limits":{"cpu":"0.2","memory":"1Gi"},"requests":{"cpu":"0.1","memory":"500Mi"}}}]}}}}
  creationTimestamp: "2023-06-07T08:49:07Z"
  generation: 1
  labels:
    app: vegastobackend
  name: vegasto-deployment
  namespace: student-t-stadler1
  resourceVersion: "150392226"
  uid: b5e3a0cf-5047-415c-8bef-a776ceeb8184
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vegastobackend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vegastobackend
    spec:
      containers:
      - image: zauner/vegastrobackend:latest
        imagePullPolicy: Always
        name: vegastro-backend
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2023-06-07T08:49:07Z"
    lastUpdateTime: "2023-06-07T08:49:07Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2023-06-07T08:49:07Z"
    lastUpdateTime: "2023-06-07T08:49:07Z"
    message: ReplicaSet "vegasto-deployment-bd97c5ff7" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
