apiVersion: apps/v1
kind: Deployment
metadata:
  name: vegasto-deployment
  labels:
    app: vegastobackend
  namespace: student-t-stadler1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vegastobackend
  template:
    metadata:
      labels:
        app: vegastobackend
    spec:
      containers:
      - name: vegastro-backend
        image: aisge/vegastro:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP 
        resources:
          limits:
            memory: "1Gi"
            cpu: "0.2"
          requests:
            memory: "500Mi"
            cpu: "0.1"
---
apiVersion: v1
kind: Service
metadata:
  name: vegastro-service
  namespace: student-t-stadler1
spec:
  selector:
    app: vegastobackend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vegastro-ingress
  namespace: student-t-stadler1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
spec:
  rules:
    - host: student.cloud.htl-leonding.ac.at
      http:
        paths:
          - path: /t.stadler/vegastro/(.*)$
            pathType: Prefix
            backend:
              service:
                name: vegastro-service
                port:
                  number: 3000