apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  labels:
    app: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
        - name: opensearch
          image: opensearchproject/opensearch
          imagePullPolicy: Always
          ports:
            - containerPort: 9200
              protocol: TCP
          resources:
            limits:
              memory: "1Gi"
              cpu: "0.2"
            requests:
              memory: "500Mi"
              cpu: "0.1"
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-dashboards
spec:
  selector:
    app: opensearch-dashboards
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opensearch
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
spec:
  rules:
    - host: student.cloud.htl-leonding.ac.at
      http:
        paths:
          - path: /t.stadler/opensearch/(.*)$
            pathType: Prefix
            backend:
              service:
                name: opensearch
                port:
                  number: 9200
