name: Ymls as Release
on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and push Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          cd Code/vegastro/backend 
          docker build -t zauner/vegastrobackend .
          docker login -u zauner -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker push zauner/vegastrobackend:latest
      - name: Create Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Code/vegastro/backend/vegastro_leocloud.yml
          tag: latest
          release_name: Release ${{ github.event.repository.updated_at }}
          overwrite: true
      - name: Upload Kubernetes File
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Code/vegastro/backend/vegastro_minikube.yml 
          tag: latest
          overwrite: true
          prerelease: true

          





