name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: stadlertobias
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  IMAGE_NAME: stadlertobias/dashboard/dashboardbackend

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          cd Code/vegastro/backend 
          docker build -t stadlertobias/vegastroBackend .
          docker login -u stadlertobias -p $DOCKER_HUB_ACCESS_TOKEN
          docker push stadlertobias/vegastroBackend:latest



