name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - test-actions

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Build and push Docker image
      #   env:
      #     DOCKER_BUILDKIT: 1
      #     DOCKER_HUB_ACCESS_TOKEN: dckr_pat_2Fu981nKJ7TV6W1n4-TOZ3foWG4
      #   run: |
      #     cd Code/vegastro/backend 
      #     docker build -t zauner/vegastrobackend .
      #     docker login -u zauner -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      #     docker push zauner/vegastrobackend:latest
      - name: Create Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: |
            Code/vegastro/backend/vegastro_leocloud.yml
            Code/vegastro/backend/vegastro_minikube.yml
          tag: ${{ github.ref }}
          release_name: Release ${{github.run_number}}
          overwrite: true
          file_glob: true




